# Generated by Django 4.2.15 on 2024-09-26 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='product_images/original/')),
                ('image_400', models.ImageField(blank=True, null=True, upload_to='product_images/400/')),
                ('image_700', models.ImageField(blank=True, null=True, upload_to='product_images/700/')),
                ('image_2000', models.ImageField(blank=True, null=True, upload_to='product_images/2000/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
            },
        ),
    ]
