# Generated by Django 4.2 on 2024-09-10 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_options_alter_product_dis_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, validators=[django.core.validators.RegexValidator(message='Slug can only contain lowercase letters, numbers, and hyphens.', regex='^[a-z0-9-]+$')]),
        ),
    ]
