# Generated by Django 4.2.15 on 2024-10-02 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_sales_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sales_count',
            field=models.PositiveIntegerField(default=119),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Slug can only contain lowercase letters, numbers, and hyphens.', regex='^[a-z0-9-]+$')]),
        ),
    ]
